name: Build Lamina Interpreter

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-2025, macos-latest]
        build_type: [Release, Debug]
        include:
          - os: ubuntu-latest
            compiler: gcc
            cmake_generator: "Unix Makefiles"
          - os: windows-2025
            compiler: msvc
            cmake_generator: "Visual Studio 17 2022"
            cmake_arch: "-A x64"
          - os: macos-latest
            compiler: clang
            cmake_generator: "Unix Makefiles"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "3.31.6"

      - name: Set up build environment (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build

      - name: Set up build environment (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew uninstall cmake || brew install cmake
          brew uninstall ninja || brew install ninja

      - name: Set up MSVC (Windows)
        if: matrix.os == 'windows-2025'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Initialize Git submodules
        run: |
          git submodule update --init --recursive

      - name: Configure CMake
        run: |
          cmake -B build ${{ matrix.cmake_arch }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -G "${{ matrix.cmake_generator }}" .

      - name: Build with CMake
        run: |
          cmake --build build --config ${{ matrix.build_type }} --parallel

      - name: Test basic functionality
        working-directory: build
        shell: bash
        run: |
          echo "Testing basic functionality..."

          # Create a simple test file
          echo 'print("Hello, Lamina!");' > test.lm
          echo 'var x = 2 + 3;' >> test.lm
          echo 'print("2 + 3 =", x);' >> test.lm

          if [ "${{ matrix.os }}" = "windows-2025" ]; then
            ./${{ matrix.build_type }}/Lamina.exe test.lm
          else
            ./Lamina test.lm
          fi

          echo "Basic test passed!"

      - name: Run example programs
        working-directory: build
        shell: bash
        run: |
          echo "Running example programs..."

          # Test all example files if they exist
          if [ -d "../examples" ]; then
            for example in ../examples/*.lm; do
              if [ -f "$example" ]; then
                echo "Testing $example..."
                if [ "${{ matrix.os }}" = "windows-2025" ]; then
                  ./bin/${{ matrix.build_type }}/lamina.exe "$example" || echo "Warning: $example failed"
                else
                  ./bin/lamina "$example" || echo "Warning: $example failed"
                fi
              fi
            done
          else
            echo "No examples directory found, skipping example tests"
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Lamina-${{ matrix.os }}-${{ matrix.build_type }}
          path: |
            bin/${{ matrix.os == 'windows-2025' && format('/bin/{0}/lamina.exe', matrix.build_type) || '/bin/lamina' }}
            lib/lamina/${{ matrix.os == 'windows-2025' && format('/lib/lamina/{0}/*.dll', matrix.build_type) || '/lib/lamina/*.so' }}
          retention-days: 30